package com.example._003springboot;

import com.example._003springboot.someservice.impl.SomeServiceImpl;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class Application implements CommandLineRunner {

    public static void main(String[] args) {
//		1.2.6 Spring Boot 中使用 ApplicationContext
//		在 main 方法中 SpringApplication.run()方法获取返回的 Spring 容器对象，再获取业务 bean
//		进行调用

        ConfigurableApplicationContext context = SpringApplication.run(Application.class, args);
        SomeServiceImpl someService = context.getBean("someService", SomeServiceImpl.class);
        someService.sayHello("李四");

    }

    @Override
    public void run(String... args) throws Exception {
//2. 容器对象创建好，执行 run
        System.out.println("输出， 在容器对象创建好后执行的代码");
        for (int i = 0; i < args.length; i++) {
            System.out.println("输出， 在容器对象创建好后执行的代码" + args[i]);

        }
    }
}
